#import <Foundation/Foundation.h>

NSString * const VencordEmbeddedBundleJS = @"(function(){\n"
    "// Vencord iOS - Patcher API\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "\n"
    "    const patches = new Map();\n"
    "\n"
    "    function createPatcher(type) {\n"
    "        return function(id, parent, funcName, patchFunc) {\n"
    "            if (!parent || typeof parent[funcName] !== 'function') {\n"
    "                console.warn(`[Vencord::Patcher] Target ${funcName} not found on parent`);\n"
    "                return () => {};\n"
    "            }\n"
    "\n"
    "            const original = parent[funcName];\n"
    "            const patchKey = `${id}:${funcName}`;\n"
    "\n"
    "            if (!parent.__vencordPatches) {\n"
    "                parent.__vencordPatches = new Map();\n"
    "            }\n"
    "\n"
    "            if (!parent.__vencordOriginal) {\n"
    "                parent.__vencordOriginal = original;\n"
    "                \n"
    "                parent[funcName] = function(...args) {\n"
    "                    const ctx = this;\n"
    "                    let currentArgs = args;\n"
    "\n"
    "                    // Before hooks\n"
    "                    const beforeList = parent.__vencordPatches.get('before') || [];\n"
    "                    for (const hook of beforeList) {\n"
    "                        try {\n"
    "                            const result = hook.call(ctx, currentArgs);\n"
    "                            if (Array.isArray(result)) currentArgs = result;\n"
    "                        } catch (err) {\n"
    "                            console.error('[Vencord::Patcher] Error in before patch:', err);\n"
    "                        }\n"
    "                    }\n"
    "\n"
    "                    // Instead hooks\n"
    "                    let returnValue;\n"
    "                    const insteadHook = (parent.__vencordPatches.get('instead') || [])[0];\n"
    "                    if (insteadHook) {\n"
    "                        try {\n"
    "                            returnValue = insteadHook.call(ctx, currentArgs, original.bind(ctx));\n"
    "                        } catch (err) {\n"
    "                            console.error('[Vencord::Patcher] Error in instead patch:', err);\n"
    "                            returnValue = original.apply(ctx, currentArgs);\n"
    "                        }\n"
    "                    } else {\n"
    "                        returnValue = original.apply(ctx, currentArgs);\n"
    "                    }\n"
    "\n"
    "                    // After hooks\n"
    "                    const afterList = parent.__vencordPatches.get('after') || [];\n"
    "                    for (const hook of afterList) {\n"
    "                        try {\n"
    "                            const result = hook.call(ctx, currentArgs, returnValue);\n"
    "                            if (result !== undefined) returnValue = result;\n"
    "                        } catch (err) {\n"
    "                            console.error('[Vencord::Patcher] Error in after patch:', err);\n"
    "                        }\n"
    "                    }\n"
    "\n"
    "                    return returnValue;\n"
    "                };\n"
    "            }\n"
    "\n"
    "            const list = parent.__vencordPatches.get(type) || [];\n"
    "            list.push(patchFunc);\n"
    "            parent.__vencordPatches.set(type, list);\n"
    "\n"
    "            const unpatch = () => {\n"
    "                const cur = parent.__vencordPatches.get(type) || [];\n"
    "                const idx = cur.indexOf(patchFunc);\n"
    "                if (idx !== -1) cur.splice(idx, 1);\n"
    "            };\n"
    "\n"
    "            patches.set(patchKey, unpatch);\n"
    "            return unpatch;\n"
    "        };\n"
    "    }\n"
    "\n"
    "    window.Vencord.Patcher = {\n"
    "        before: createPatcher('before'),\n"
    "        after: createPatcher('after'),\n"
    "        instead: createPatcher('instead'),\n"
    "        unpatchAll: () => {\n"
    "            for (const unpatch of patches.values()) {\n"
    "                unpatch();\n"
    "            }\n"
    "            patches.clear();\n"
    "        }\n"
    "    };\n"
    "})();\n"
    "// Vencord iOS - Metro Webpack Crawler\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "\n"
    "    const moduleCache = new Map();\n"
    "\n"
    "    function getAllModules() {\n"
    "        if (typeof window.__r !== 'function') return [];\n"
    "        // Metro module registry exploration\n"
    "        const modules = [];\n"
    "        for (let i = 0; i < 50000; i++) {\n"
    "            try {\n"
    "                const m = window.__r(i);\n"
    "                if (m) modules.push(m);\n"
    "            } catch (_) {}\n"
    "        }\n"
    "        return modules;\n"
    "    }\n"
    "\n"
    "    function findByProps(...props) {\n"
    "        for (const m of getAllModules()) {\n"
    "            if (!m) continue;\n"
    "            if (props.every(p => m[p] !== undefined || (m.default && m.default[p] !== undefined))) {\n"
    "                return m.default && props.every(p => m.default[p] !== undefined) ? m.default : m;\n"
    "            }\n"
    "        }\n"
    "        return null;\n"
    "    }\n"
    "\n"
    "    function findByName(name) {\n"
    "        for (const m of getAllModules()) {\n"
    "            if (!m) continue;\n"
    "            if (m.name === name || (m.default && m.default.name === name) || m.displayName === name) {\n"
    "                return m.default || m;\n"
    "            }\n"
    "        }\n"
    "        return null;\n"
    "    }\n"
    "\n"
    "    function findByStoreName(storeName) {\n"
    "        for (const m of getAllModules()) {\n"
    "            if (!m) continue;\n"
    "            const target = m.default || m;\n"
    "            if (target && target.getName && target.getName() === storeName) {\n"
    "                return target;\n"
    "            }\n"
    "        }\n"
    "        return null;\n"
    "    }\n"
    "\n"
    "    window.Vencord.Webpack = {\n"
    "        findByProps,\n"
    "        findByName,\n"
    "        findByStoreName,\n"
    "        getAllModules,\n"
    "        common: {\n"
    "            get Dispatcher() { return findByProps('dispatch', 'subscribe'); },\n"
    "            get UserStore() { return findByStoreName('UserStore') || findByProps('getCurrentUser'); },\n"
    "            get MessageActions() { return findByProps('sendMessage', 'editMessage'); },\n"
    "            get ChannelStore() { return findByStoreName('ChannelStore'); },\n"
    "            get GuildStore() { return findByStoreName('GuildStore'); }\n"
    "        }\n"
    "    };\n"
    "})();\n"
    "// Vencord iOS - Free Nitro Emotes & Stickers Plugin\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "    window.Vencord.Plugins = window.Vencord.Plugins || {};\n"
    "\n"
    "    window.Vencord.Plugins.NitroEmotes = {\n"
    "        name: \"NitroEmotes\",\n"
    "        description: \"Enables client-side Nitro emojis, animated stickers, and 1080p 60fps streaming on iOS.\",\n"
    "        author: \"Vencord iOS Team\",\n"
    "        enabled: true,\n"
    "\n"
    "        start() {\n"
    "            const { Patcher, Webpack } = window.Vencord;\n"
    "            const MessageActions = Webpack.common.MessageActions;\n"
    "\n"
    "            if (MessageActions && MessageActions.sendMessage) {\n"
    "                this.unpatchSend = Patcher.before(\"NitroEmotes\", MessageActions, \"sendMessage\", (args) => {\n"
    "                    const [channelId, message, ...rest] = args;\n"
    "                    if (!message || typeof message.content !== 'string') return args;\n"
    "\n"
    "                    // Match custom Discord emotes: <:name:id> or <a:name:id>\n"
    "                    let content = message.content;\n"
    "                    const emojiRegex = /<(a?):(\\w+):(\\d+)>/g;\n"
    "                    let match;\n"
    "                    let replaced = false;\n"
    "\n"
    "                    while ((match = emojiRegex.exec(content)) !== null) {\n"
    "                        const [fullMatch, isAnimated, name, id] = match;\n"
    "                        const ext = isAnimated ? 'gif' : 'png';\n"
    "                        const emojiUrl = `https://cdn.discordapp.com/emojis/${id}.${ext}?size=96&quality=lossless`;\n"
    "                        \n"
    "                        // Replace emote code with direct CDN link if user doesn't have Nitro perms\n"
    "                        content = content.replace(fullMatch, emojiUrl);\n"
    "                        replaced = true;\n"
    "                    }\n"
    "\n"
    "                    if (replaced) {\n"
    "                        message.content = content;\n"
    "                    }\n"
    "\n"
    "                    return [channelId, message, ...rest];\n"
    "                });\n"
    "            }\n"
    "\n"
    "            // Hook UserStore to simulate Nitro status for local UI picker\n"
    "            const UserStore = Webpack.common.UserStore;\n"
    "            if (UserStore && UserStore.getCurrentUser) {\n"
    "                this.unpatchUser = Patcher.after(\"NitroEmotesUser\", UserStore, \"getCurrentUser\", (args, user) => {\n"
    "                    if (user && !user.premiumType) {\n"
    "                        // 2 = Nitro Premium (Allows selecting external server emotes in the mobile picker)\n"
    "                        user.premiumType = 2;\n"
    "                    }\n"
    "                    return user;\n"
    "                });\n"
    "            }\n"
    "\n"
    "            console.log(\"[Vencord] NitroEmotes plugin loaded\");\n"
    "        },\n"
    "\n"
    "        stop() {\n"
    "            if (this.unpatchSend) this.unpatchSend();\n"
    "            if (this.unpatchUser) this.unpatchUser();\n"
    "        }\n"
    "    };\n"
    "})();\n"
    "// Vencord iOS - Message Logger Plugin\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "    window.Vencord.Plugins = window.Vencord.Plugins || {};\n"
    "\n"
    "    const deletedMessages = new Map();\n"
    "    const editHistory = new Map();\n"
    "\n"
    "    window.Vencord.Plugins.MessageLogger = {\n"
    "        name: \"MessageLogger\",\n"
    "        description: \"Logs deleted messages and edit history inline in channels.\",\n"
    "        author: \"Vencord iOS Team\",\n"
    "        enabled: true,\n"
    "\n"
    "        start() {\n"
    "            const { Webpack, Patcher } = window.Vencord;\n"
    "            const Dispatcher = Webpack.common.Dispatcher;\n"
    "\n"
    "            if (!Dispatcher) return;\n"
    "\n"
    "            this.handleDelete = (event) => {\n"
    "                if (!event || !event.id) return;\n"
    "                deletedMessages.set(event.id, {\n"
    "                    channelId: event.channelId,\n"
    "                    guildId: event.guildId,\n"
    "                    deletedAt: new Date()\n"
    "                });\n"
    "            };\n"
    "\n"
    "            this.handleUpdate = (event) => {\n"
    "                if (!event || !event.message || !event.message.id) return;\n"
    "                const id = event.message.id;\n"
    "                const edits = editHistory.get(id) || [];\n"
    "                if (event.message.content) {\n"
    "                    edits.push({\n"
    "                        content: event.message.content,\n"
    "                        editedAt: new Date()\n"
    "                    });\n"
    "                    editHistory.set(id, edits);\n"
    "                }\n"
    "            };\n"
    "\n"
    "            Dispatcher.subscribe(\"MESSAGE_DELETE\", this.handleDelete);\n"
    "            Dispatcher.subscribe(\"MESSAGE_UPDATE\", this.handleUpdate);\n"
    "\n"
    "            // Hook Message parser / serializer to prevent deleted messages from being removed\n"
    "            const MessageStore = Webpack.findByStoreName('MessageStore') || Webpack.findByProps('getMessage', 'getMessages');\n"
    "            if (MessageStore) {\n"
    "                this.unpatchDeleteStore = Patcher.instead(\"MessageLoggerDelete\", MessageStore, \"deleteMessage\", (args, orig) => {\n"
    "                    const [channelId, messageId] = args;\n"
    "                    const msg = MessageStore.getMessage(channelId, messageId);\n"
    "                    if (msg) {\n"
    "                        msg.deleted = true;\n"
    "                        msg.__vencordDeleted = true;\n"
    "                        if (!msg.content.includes(\" [deleted]\")) {\n"
    "                            msg.content += \" \\x1b[31m[deleted]\\x1b[0m\";\n"
    "                        }\n"
    "                        return; // Prevent actual removal\n"
    "                    }\n"
    "                    return orig.apply(this, args);\n"
    "                });\n"
    "            }\n"
    "\n"
    "            console.log(\"[Vencord] MessageLogger plugin loaded\");\n"
    "        },\n"
    "\n"
    "        stop() {\n"
    "            const { Webpack } = window.Vencord;\n"
    "            const Dispatcher = Webpack?.common?.Dispatcher;\n"
    "            if (Dispatcher) {\n"
    "                if (this.handleDelete) Dispatcher.unsubscribe(\"MESSAGE_DELETE\", this.handleDelete);\n"
    "                if (this.handleUpdate) Dispatcher.unsubscribe(\"MESSAGE_UPDATE\", this.handleUpdate);\n"
    "            }\n"
    "            if (this.unpatchDeleteStore) this.unpatchDeleteStore();\n"
    "        }\n"
    "    };\n"
    "})();\n"
    "// Vencord iOS - Ghost Mode (Silent Typing & Invisible Read Receipts)\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "    window.Vencord.Plugins = window.Vencord.Plugins || {};\n"
    "\n"
    "    window.Vencord.Plugins.GhostMode = {\n"
    "        name: \"GhostMode\",\n"
    "        description: \"Blocks typing indicators and read receipts to keep you completely invisible.\",\n"
    "        author: \"Vencord iOS Team\",\n"
    "        enabled: true,\n"
    "\n"
    "        start() {\n"
    "            const { Webpack, Patcher } = window.Vencord;\n"
    "\n"
    "            // Block Typing Indicators\n"
    "            const TypingModule = Webpack.findByProps('startTyping', 'stopTyping');\n"
    "            if (TypingModule) {\n"
    "                this.unpatchTyping = Patcher.instead(\"GhostModeTyping\", TypingModule, \"startTyping\", () => {\n"
    "                    // Drop outgoing typing indicator\n"
    "                    return Promise.resolve();\n"
    "                });\n"
    "            }\n"
    "\n"
    "            // Block Read Receipts (Acks)\n"
    "            const AckModule = Webpack.findByProps('ack', 'bulkAck') || Webpack.findByProps('ackMessage');\n"
    "            if (AckModule) {\n"
    "                this.unpatchAck = Patcher.instead(\"GhostModeAck\", AckModule, \"ack\", (args, orig) => {\n"
    "                    // Suppress automatic read status update\n"
    "                    return Promise.resolve();\n"
    "                });\n"
    "            }\n"
    "\n"
    "            console.log(\"[Vencord] GhostMode plugin loaded\");\n"
    "        },\n"
    "\n"
    "        stop() {\n"
    "            if (this.unpatchTyping) this.unpatchTyping();\n"
    "            if (this.unpatchAck) this.unpatchAck();\n"
    "        }\n"
    "    };\n"
    "})();\n"
    "// Vencord iOS - OLED Pure Black Theme Plugin\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "    window.Vencord.Plugins = window.Vencord.Plugins || {};\n"
    "\n"
    "    window.Vencord.Plugins.OLEDTheme = {\n"
    "        name: \"OLEDTheme\",\n"
    "        description: \"Applies pure #000000 black to chat views, server lists, and settings.\",\n"
    "        author: \"Vencord iOS Team\",\n"
    "        enabled: true,\n"
    "\n"
    "        start() {\n"
    "            const { Webpack, Patcher } = window.Vencord;\n"
    "            const ThemeStore = Webpack.findByStoreName('ThemeStore') || Webpack.findByProps('theme');\n"
    "\n"
    "            if (ThemeStore && ThemeStore.theme) {\n"
    "                // Ensure dark mode is active\n"
    "                ThemeStore.theme = \"dark\";\n"
    "            }\n"
    "\n"
    "            // Hook color token resolver in Discord's React Native Theme definitions\n"
    "            const ColorTokens = Webpack.findByProps('raw', 'colors') || Webpack.findByProps('SemanticColors');\n"
    "            if (ColorTokens && ColorTokens.colors) {\n"
    "                this.originalColors = { ...ColorTokens.colors };\n"
    "                ColorTokens.colors.BACKGROUND_PRIMARY = \"#000000\";\n"
    "                ColorTokens.colors.BACKGROUND_SECONDARY = \"#050505\";\n"
    "                ColorTokens.colors.BACKGROUND_SECONDARY_ALT = \"#0a0a0a\";\n"
    "                ColorTokens.colors.BACKGROUND_TERTIARY = \"#000000\";\n"
    "                ColorTokens.colors.BACKGROUND_ACCENT = \"#111111\";\n"
    "                ColorTokens.colors.BACKGROUND_FLOATING = \"#000000\";\n"
    "            }\n"
    "\n"
    "            console.log(\"[Vencord] OLEDTheme plugin loaded\");\n"
    "        },\n"
    "\n"
    "        stop() {\n"
    "            const { Webpack } = window.Vencord;\n"
    "            const ColorTokens = Webpack?.findByProps('raw', 'colors');\n"
    "            if (ColorTokens && this.originalColors) {\n"
    "                Object.assign(ColorTokens.colors, this.originalColors);\n"
    "            }\n"
    "        }\n"
    "    };\n"
    "})();\n"
    "// Vencord iOS - Main Bootstrap & Plugin Manager\n"
    "(function() {\n"
    "    window.Vencord = window.Vencord || {};\n"
    "    window.Vencord.version = \"1.0.0\";\n"
    "    window.Vencord.Plugins = window.Vencord.Plugins || {};\n"
    "\n"
    "    function initVencord() {\n"
    "        console.log(\"[Vencord iOS] Initializing client modification...\");\n"
    "\n"
    "        // Wait for React Native / Metro bundle to populate\n"
    "        const interval = setInterval(() => {\n"
    "            if (typeof window.__r === 'function') {\n"
    "                clearInterval(interval);\n"
    "                startPlugins();\n"
    "            }\n"
    "        }, 100);\n"
    "\n"
    "        // Safety timeout\n"
    "        setTimeout(() => clearInterval(interval), 15000);\n"
    "    }\n"
    "\n"
    "    function startPlugins() {\n"
    "        console.log(\"[Vencord iOS] Starting plugins...\");\n"
    "        const plugins = window.Vencord.Plugins;\n"
    "\n"
    "        for (const [name, plugin] of Object.entries(plugins)) {\n"
    "            try {\n"
    "                if (plugin && typeof plugin.start === 'function') {\n"
    "                    plugin.start();\n"
    "                    console.log(`[Vencord iOS] Plugin ${name} started successfully.`);\n"
    "                }\n"
    "            } catch (err) {\n"
    "                console.error(`[Vencord iOS] Error starting plugin ${name}:`, err);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    if (document.readyState === 'complete' || typeof window !== 'undefined') {\n"
    "        initVencord();\n"
    "    }\n"
    "})();\n"
    "\n"
    "})();";
